version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./app:/app/app
    restart: unless-stopped
