"""add updated_at ke table topup_package_model

Revision ID: 0deb809d6fe9
Revises: 96ca596e6c62
Create Date: 2025-12-12 14:44:09.768695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0deb809d6fe9'
down_revision: Union[str, None] = '96ca596e6c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('topup_packages', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topup_packages', 'updated_at')
    op.drop_column('plans', 'updated_at')
    # ### end Alembic commands ###
