"""remove logo column from company table

Revision ID: 0f4c09aa8366
Revises: f7bf173ecb5e
Create Date: 2025-10-30 13:28:43.919192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4c09aa8366'
down_revision: Union[str, None] = 'f7bf173ecb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Company', 'logo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Company', sa.Column('logo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
