"""add column match_score dan response_time_ms ke tabel chatlog

Revision ID: 161fc3a36f94
Revises: 4e07830eb99c
Create Date: 2025-12-08 21:46:53.162512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161fc3a36f94'
down_revision: Union[str, None] = '4e07830eb99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chatlogs', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('Chatlogs', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chatlogs', 'response_time_ms')
    op.drop_column('Chatlogs', 'match_score')
    # ### end Alembic commands ###
