"""update

Revision ID: 2cc2c62e4416
Revises: 3d4e513a20b3
Create Date: 2025-12-22 16:22:19.951542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc2c62e4416'
down_revision: Union[str, None] = '3d4e513a20b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Users_email', table_name='Users')
    op.drop_column('Users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_Users_email', 'Users', ['email'], unique=True)
    # ### end Alembic commands ###
