"""add table recommended_for

Revision ID: 3771f684a3d3
Revises: a11d8d9c2f1a
Create Date: 2025-12-01 15:23:31.130937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3771f684a3d3'
down_revision: Union[str, None] = 'a11d8d9c2f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('recomended_for', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'recomended_for')
    # ### end Alembic commands ###
