"""remove_speech_columns_from_chatlogs

Revision ID: 3d4e513a20b3
Revises: 8dc2944e8e3d
Create Date: 2025-12-19 20:38:58.019963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4e513a20b3'
down_revision: Union[str, None] = '8dc2944e8e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chatlogs', 'stt_request_id')
    op.drop_column('Chatlogs', 'input_type')
    op.drop_column('Chatlogs', 'input_audio_path')
    op.drop_column('Chatlogs', 'tts_request_id')
    op.drop_column('Chatlogs', 'input_duration_ms')
    op.drop_column('Chatlogs', 'output_audio_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chatlogs', sa.Column('output_audio_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Chatlogs', sa.Column('input_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Chatlogs', sa.Column('tts_request_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Chatlogs', sa.Column('input_audio_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Chatlogs', sa.Column('input_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('Chatlogs', sa.Column('stt_request_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
