"""drop division table and add division column to user

Revision ID: 4ce0247f0683
Revises: 298a099d748c
Create Date: 2025-11-07 11:30:50.760966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce0247f0683'
down_revision: Union[str, None] = '298a099d748c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Users_division_id_fkey', 'Users', type_='foreignkey')
    op.drop_column('Users', 'division_id')
    op.drop_table('Division')
    # op.add_column('Chatlogs', sa.Column('referenced_document_ids', sa.JSON(), nullable=True))
    op.alter_column('Chatlogs', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('Users', sa.Column('division', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('division_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Users_division_id_fkey', 'Users', 'Division', ['division_id'], ['id'])
    op.drop_column('Users', 'division')
    op.alter_column('Chatlogs', 'question',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('Chatlogs', 'referenced_document_ids')
    op.create_table('Division',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Division_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], name='Division_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Division_pkey')
    )
    # ### end Alembic commands ###
