"""remove metadata_json coloum

Revision ID: 4e07830eb99c
Revises: 3771f684a3d3
Create Date: 2025-12-03 12:16:52.239364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e07830eb99c'
down_revision: Union[str, None] = '3771f684a3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'metadata_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
