"""add column payment_url dan receipt_json ke table transaction

Revision ID: 51047d98f0ab
Revises: 8e64617c0e8d
Create Date: 2025-11-25 15:13:24.361405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51047d98f0ab'
down_revision: Union[str, None] = '8e64617c0e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_url')
    # ### end Alembic commands ###
