"""remove is_active_in_company from users table

Revision ID: 53ecef7cbab4
Revises: 0f4c09aa8366
Create Date: 2025-10-30 16:20:38.526107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ecef7cbab4'
down_revision: Union[str, None] = '0f4c09aa8366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Company', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('Users', 'is_active_in_company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_active_in_company', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Company', 'is_active')
    # ### end Alembic commands ###
