"""memindahkan kolom pic phone number dari table users ke table company

Revision ID: 5efedaa6c90f
Revises: b24f31f10d8a
Create Date: 2025-11-01 09:26:28.954884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efedaa6c90f'
down_revision: Union[str, None] = 'b24f31f10d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Company', sa.Column('pic_phone_number', sa.String(length=50), nullable=True))
    op.drop_column('Users', 'pic_phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('pic_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('Company', 'pic_phone_number')
    # ### end Alembic commands ###
