"""add_activation_email_sent_to_company

Revision ID: 8dc2944e8e3d
Revises: 93bfe8f110e0
Create Date: 2025-12-18 22:52:46.967491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc2944e8e3d'
down_revision: Union[str, None] = '93bfe8f110e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Company', sa.Column('activation_email_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Company', 'activation_email_sent')
    # ### end Alembic commands ###
