"""add column document limit

Revision ID: 8e64617c0e8d
Revises: aac8344e352a
Create Date: 2025-11-25 14:41:11.481820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e64617c0e8d'
down_revision: Union[str, None] = 'aac8344e352a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('document_quota', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'document_quota')
    # ### end Alembic commands ###
