"""update column in users table

Revision ID: 8ee479664365
Revises: 
Create Date: 2025-10-30 22:45:42.398557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee479664365'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('division_id', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint('Users_Divisionid_fkey', 'Users', type_='foreignkey')
    op.create_foreign_key(None, 'Users', 'Division', ['division_id'], ['id'])
    op.drop_column('Users', 'Divisionid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('Divisionid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.create_foreign_key('Users_Divisionid_fkey', 'Users', 'Division', ['Divisionid'], ['id'])
    op.drop_column('Users', 'is_active')
    op.drop_column('Users', 'division_id')
    # ### end Alembic commands ###
