"""add email column on users table

Revision ID: 8fa8fdd34db0
Revises: 2cc2c62e4416
Create Date: 2025-12-28 11:40:21.653708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa8fdd34db0'
down_revision: Union[str, None] = '2cc2c62e4416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_column('Users', 'email')
    # ### end Alembic commands ###
