"""menambahkan kolom input_type, input_audio_path, output_audio_path, stt_request_id, tts_request_id, input_duration_ms

Revision ID: 93bfe8f110e0
Revises: 0deb809d6fe9
Create Date: 2025-12-15 22:09:52.184085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bfe8f110e0'
down_revision: Union[str, None] = '0deb809d6fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chatlogs', sa.Column('input_type', sa.String(length=20), nullable=True))
    op.add_column('Chatlogs', sa.Column('input_audio_path', sa.String(), nullable=True))
    op.add_column('Chatlogs', sa.Column('output_audio_path', sa.String(), nullable=True))
    op.add_column('Chatlogs', sa.Column('stt_request_id', sa.String(), nullable=True))
    op.add_column('Chatlogs', sa.Column('tts_request_id', sa.String(), nullable=True))
    op.add_column('Chatlogs', sa.Column('input_duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chatlogs', 'input_duration_ms')
    op.drop_column('Chatlogs', 'tts_request_id')
    op.drop_column('Chatlogs', 'stt_request_id')
    op.drop_column('Chatlogs', 'output_audio_path')
    op.drop_column('Chatlogs', 'input_audio_path')
    op.drop_column('Chatlogs', 'input_type')
    # ### end Alembic commands ###
