"""add table topup_packages

Revision ID: 96ca596e6c62
Revises: 161fc3a36f94
Create Date: 2025-12-11 09:33:22.150066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ca596e6c62'
down_revision: Union[str, None] = '161fc3a36f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topup_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(), nullable=False),
    sa.Column('questions', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_type')
    )
    op.create_index(op.f('ix_topup_packages_id'), 'topup_packages', ['id'], unique=False)
    op.create_index('ix_topup_packages_is_active', 'topup_packages', ['is_active'], unique=False)
    op.create_index('ix_topup_packages_type', 'topup_packages', ['package_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topup_packages_type', table_name='topup_packages')
    op.drop_index('ix_topup_packages_is_active', table_name='topup_packages')
    op.drop_index(op.f('ix_topup_packages_id'), table_name='topup_packages')
    op.drop_table('topup_packages')
    # ### end Alembic commands ###
