"""Add company_email to Company model

Revision ID: a0524da99c5c
Revises: fdc720b12797
Create Date: 2025-11-18 10:29:27.988728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0524da99c5c'
down_revision: Union[str, None] = 'fdc720b12797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Company', sa.Column('company_email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'Company', ['company_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Company', type_='unique')
    op.drop_column('Company', 'company_email')
    # ### end Alembic commands ###
