"""delete receipt_json

Revision ID: a11d8d9c2f1a
Revises: 51047d98f0ab
Create Date: 2025-11-25 15:35:01.386490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11d8d9c2f1a'
down_revision: Union[str, None] = '51047d98f0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'receipt_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receipt_json', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
