"""indexing some table

Revision ID: aac8344e352a
Revises: 9c6b5f2a7d8e
Create Date: 2025-11-24 21:00:19.772306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac8344e352a'
down_revision: Union[str, None] = '9c6b5f2a7d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_activity_logs_company_timestamp', 'Activity_logs', ['company_id', 'timestamp'], unique=False)
    op.create_index('ix_activity_logs_company_type', 'Activity_logs', ['company_id', 'activity_type_category'], unique=False)
    op.create_index('ix_chatlogs_company_created', 'Chatlogs', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_chatlogs_company_user', 'Chatlogs', ['company_id', 'UsersId'], unique=False)
    op.create_index('ix_company_created_at', 'Company', ['created_at'], unique=False)
    op.create_index('ix_company_is_active', 'Company', ['is_active'], unique=False)
    op.create_index('ix_documents_company_status', 'Documents', ['company_id', 'status'], unique=False)
    op.create_index('ix_documents_company_updated', 'Documents', ['company_id', 'updated_at'], unique=False)
    op.create_index('ix_users_company_active', 'Users', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_users_company_role', 'Users', ['company_id', 'role'], unique=False)
    op.create_index('ix_users_role_active', 'Users', ['role', 'is_active'], unique=False)
    op.create_index('ix_plans_is_active', 'plans', ['is_active'], unique=False)
    op.create_index('ix_plans_price', 'plans', ['price'], unique=False)
    op.create_index('ix_subscriptions_plan_status', 'subscriptions', ['plan_id', 'status'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('ix_transactions_company_created', 'transactions', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_transactions_company_status_type', 'transactions', ['company_id', 'status', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_company_status_type', table_name='transactions')
    op.drop_index('ix_transactions_company_created', table_name='transactions')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_plan_status', table_name='subscriptions')
    op.drop_index('ix_plans_price', table_name='plans')
    op.drop_index('ix_plans_is_active', table_name='plans')
    op.drop_index('ix_users_role_active', table_name='Users')
    op.drop_index('ix_users_company_role', table_name='Users')
    op.drop_index('ix_users_company_active', table_name='Users')
    op.drop_index('ix_documents_company_updated', table_name='Documents')
    op.drop_index('ix_documents_company_status', table_name='Documents')
    op.drop_index('ix_company_is_active', table_name='Company')
    op.drop_index('ix_company_created_at', table_name='Company')
    op.drop_index('ix_chatlogs_company_user', table_name='Chatlogs')
    op.drop_index('ix_chatlogs_company_created', table_name='Chatlogs')
    op.drop_index('ix_activity_logs_company_type', table_name='Activity_logs')
    op.drop_index('ix_activity_logs_company_timestamp', table_name='Activity_logs')
    # ### end Alembic commands ###
