"""menambahkan kolom tags dan uploaded_at di table documents

Revision ID: b24f31f10d8a
Revises: 8ee479664365
Create Date: 2025-10-31 21:02:55.819138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b24f31f10d8a'
down_revision: Union[str, None] = '8ee479664365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Documents', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('Documents', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Documents', 'uploaded_at')
    op.drop_column('Documents', 'tags')
    # ### end Alembic commands ###
