"""add created_at to users table

Revision ID: bd191316a9e9
Revises: d8ca9bbba48e
Create Date: 2025-11-23 21:16:56.132701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd191316a9e9'
down_revision: Union[str, None] = 'd8ca9bbba48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_company_id_chatlogs_index', table_name='Chatlogs')
    op.drop_index('idx_created_at_chatlogs_index', table_name='Chatlogs')
    op.drop_index('idx_company_id_conversation_index', table_name='Conversation')
    op.drop_index('idx_company_id_documents_index', table_name='Documents')
    op.add_column('Users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index('idx_email_users_index', table_name='Users')
    op.drop_index('idx_username_users_index', table_name='Users')
    op.drop_index('idx_company_id_index', table_name='subscriptions')
    op.drop_index('idx_plan_id_index', table_name='subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_plan_id_index', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_company_id_index', 'subscriptions', ['company_id'], unique=False)
    op.create_index('idx_username_users_index', 'Users', ['username'], unique=False)
    op.create_index('idx_email_users_index', 'Users', ['email'], unique=False)
    op.drop_column('Users', 'created_at')
    op.create_index('idx_company_id_documents_index', 'Documents', ['company_id'], unique=False)
    op.create_index('idx_company_id_conversation_index', 'Conversation', ['company_id'], unique=False)
    op.create_index('idx_created_at_chatlogs_index', 'Chatlogs', ['created_at'], unique=False)
    op.create_index('idx_company_id_chatlogs_index', 'Chatlogs', ['company_id'], unique=False)
    # ### end Alembic commands ###
