"""Add updated_at to Documents table

Revision ID: c893106edbe1
Revises: a0524da99c5c
Create Date: 2025-11-18 11:13:57.297751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c893106edbe1'
down_revision: Union[str, None] = 'a0524da99c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Documents', 'updated_at')
    # ### end Alembic commands ###
