"""update

Revision ID: d8ca9bbba48e
Revises: c893106edbe1
Create Date: 2025-11-21 09:04:12.287933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ca9bbba48e'
down_revision: Union[str, None] = 'c893106edbe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('question_quota', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('allow_custom_prompts', sa.Boolean(), nullable=True),
    sa.Column('api_access', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('current_question_usage', sa.Integer(), nullable=True),
    sa.Column('top_up_quota', sa.Integer(), nullable=True),
    sa.Column('payment_gateway_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_payment_gateway_reference'), 'subscriptions', ['payment_gateway_reference'], unique=False)
    op.alter_column('Company', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'Company', ['code'])
    # Add company_id as nullable first so existing rows can be backfilled
    op.add_column('Conversation', sa.Column('company_id', sa.Integer(), nullable=True))
    # Backfill company_id from existing chatlogs (assumes chatlogs already store company_id)
    op.execute("""
        UPDATE "Conversation" c
        SET company_id = cl.company_id
        FROM (
            SELECT conversation_id, MAX(company_id) AS company_id
            FROM "Chatlogs"
            GROUP BY conversation_id
        ) cl
        WHERE c.id = cl.conversation_id
    """)
    # For any remaining conversations without chatlogs, fallback to the first company to satisfy NOT NULL + FK
    op.execute("""
        WITH fallback_company AS (
            SELECT id AS company_id FROM "Company" ORDER BY id LIMIT 1
        )
        UPDATE "Conversation" c
        SET company_id = f.company_id
        FROM fallback_company f
        WHERE c.company_id IS NULL
    """)
    op.alter_column('Conversation', 'company_id', nullable=False)
    op.create_foreign_key(None, 'Conversation', 'Company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Conversation', type_='foreignkey')
    op.drop_column('Conversation', 'company_id')
    op.drop_constraint(None, 'Company', type_='unique')
    op.alter_column('Company', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_subscriptions_payment_gateway_reference'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
