"""Add referenced_document_ids to Chatlogs

Revision ID: e86c506b3e6c
Revises: 
Create Date: 2025-11-03 23:23:38.845673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86c506b3e6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('Conversation',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('title', sa.String(length=255), nullable=False),
    # sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_Conversation_id'), 'Conversation', ['id'], unique=False)
    # op.drop_table('Embeddings') # Removed this line as the table does not exist
    # op.add_column('Chatlogs', sa.Column('referenced_document_ids', sa.JSON(), nullable=True)) # Removed this line as the column already exists
    op.alter_column('Chatlogs', 'conversation_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'Chatlogs', 'Conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Chatlogs', type_='foreignkey')
    op.alter_column('Chatlogs', 'conversation_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('Chatlogs', 'referenced_document_ids')
    op.create_table('Embeddings',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Embeddings_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('vector_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['Documents.id'], name='Embeddings_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Embeddings_pkey')
    )
    op.drop_index(op.f('ix_Conversation_id'), table_name='Conversation')
    op.drop_table('Conversation')
    # ### end Alembic commands ###
