"""update table

Revision ID: f89818c1e63b
Revises: 4ce0247f0683
Create Date: 2025-11-10 15:25:35.936641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89818c1e63b'
down_revision: Union[str, None] = '4ce0247f0683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('Users', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'reset_token_expiry')
    op.drop_column('Users', 'reset_token')
    # ### end Alembic commands ###
