"""add is_archived to conversation

Revision ID: fdc720b12797
Revises: d116123af7eb
Create Date: 2025-11-16 11:16:56.514979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc720b12797'
down_revision: Union[str, None] = 'd116123af7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Conversation', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Conversation', 'is_archived')
    # ### end Alembic commands ###
